###################################################
## Various MQTT sensors
## https://www.home-assistant.io/components/binary_sensor.mqtt/
###################################################

- platform: mqtt
  name: "Main Door"
  state_topic: "smartthings/Main Door/contact"
  device_class: door
  payload_on: "open"
  payload_off: "closed"
