###################################################
## Various MQTT sensors
###################################################

- platform: mqtt
  name: "Main Door"
  state_topic: "smartthings/Main Door/contact"
  device_class: door
