###################################
##  Uses IFTTT to notify me of bad logins.
###################################

- alias: Login Failure
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"

  action:
    - service: script.notify_engine
      data_template:
        value1: "{{ states.persistent_notification.httplogin.attributes.message }}"
        value2: 'url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.httplogin.attributes.message.split("from")[1]}}'
        who: 'harshit'

    - service: script.tweet_engine
      data_template:
        tweet: >
          {{ [
          "Seriously, I am a Smart Home. I am logging your hack attempt.",
          "If you do not know the password, you get locked out and IP banned.",
          "Three Strikes and you are OUT! IP Banned."
          ] | random + "#Security"}}
