###################################
## @CCOSTAN
## Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################

- alias: Door Chime
  trigger:
    - platform: state
      entity_id:
        - group.entry_points

  condition:
    - condition: state
      entity_id: group.family
      state: 'home'

  action:
    - service: media_player.turn_on
      entity_id: media_player.media_room

    - delay: '00:00:05'

    - service: media_player.volume_set
      entity_id:
        - media_player.media_room
      data_template:
        volume_level: >
          {% if now().strftime("%H")|int < 12 and now().strftime("%H")|int > 6%}
          0.45
          {% elif now().strftime("%H")|int > 12 and now().strftime("%H")|int < 17%}
          0.7
          {% else %}
          0.40
          {% endif %}

    - service: media_player.play_media
      data_template:
        entity_id: >
          media_player.media_room
        media_content_id: >
          {% if trigger.to_state.state == 'on' %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/one-tone-chime.mp3
          {% else %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/two-tone-chime.mp3
          {% endif %}
        media_content_type: audio/mp4
