##############################################################################
###  Detect when things are on and forgotten about. Like any Good Watchdog.
##############################################################################

##############################################################################

- alias: "Notify if IP changes"
  initial_state: 'on'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.ipchange
      from: 'False'
      to: 'True'
  action:
    - service: script.notify_engine
      data_template:
        value1: 'Changed IP address:'
        value2: "New IP: {{ states('sensor.exteral_ip') }}"
        # value3: ' - Be sure to Change DNS!'
        who: 'harshit'

    - service: script.tweet_engine
      data_template:
        tweet: >
          {{ [
          "That's weird. Looks like my IP address changed. @harshit_ps, please check it out.",
          "Looks like my IP address changed. Updating @duckdns"
          ] | random + " #HomeAutomation"}}
##############################################################################
