- alias: "Update Available Notification"
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater

  condition:
    - condition: template
      value_template: "{{ states('updater.updater') != 'unknown' }}"

  action:
    - service: script.notify_engine
      data_template:
        value1: "Home Assistant {{ states.updater.updater.state }} is now available. Current v{{ sensor.ha_installed_version }}"
        who: 'harshit'

    - service: script.tweet_engine_image
      data_template:
        tweet: "New version of @Home_Assistant! Cannot wait for @harshit_ps to install it! - {{ states('updater.updater') }}"
        image: >-
          {{ [
          "/config/www/custom_ui/floorplan/images/branding/repo_ad.png",
          "/config/www/custom_ui/floorplan/images/branding/repo_ad2.png",
          "/config/www/custom_ui/floorplan/images/branding/repo_ad3.png",
          "/config/www/custom_ui/floorplan/images/branding/repo_ad4.png"
          ] | random }}

    - service: notify.html5
      data_template:
        title: "Update Available"
        message: "Home Assistant {{ states('updater.updater') }} is available. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
        data:
          url: "https://www.home-assistant.io/docs/installation/raspberry-pi/#updating"

    - service: persistent_notification.create
      data:
        title: "Update Available"
        message: "Home Assistant {{ states('updater.updater') }} is available. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
        notification_id: "update_available"
