##############################################################################
###  Detect when things are on and forgotten about. Like any Good Watchdog.
##############################################################################


- alias: Forgotten Lights WatchDog
  trigger:
    - platform: state
      entity_id: group.all_lights
      to: 'on'
      for: '01:00:00'
    - platform: state
      entity_id: group.all_switches
      to: 'on'
      for: '01:00:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'


  action:
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

- alias: Daytime Lights WatchDog
  trigger:
    - platform: time
      minutes: 10
      seconds: 20
    - platform: time
      minutes: 40
      seconds: 00

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'

#Turn it off!
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id:
          - group.hallway_lights
          - group.bedroom_lights
