homeassistant:
  name: SanghviHA
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: America/New_York

  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    automation.*watchdog*:
      icon: mdi:timer
    sensor.dark_sky_*:
      homebridge_hidden: true
    scene.month_*_colors:
      hidden: true
      homebridge_hidden: true

  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_api_password
   - type: trusted_networks
     trusted_networks:
       - 192.168.1.0/24

# Enables configuration UI
config:

system_health:

cloud:
  alexa:
    filter:
      include_entities:
        # - group.all_lights
        # - group.all_switches
        # - group.interior_lights
        # - group.bedroom_lights
        # - group.living_room_lights
        # - group.living_room_accents
        # - group.dinette_lights
        # - group.dining_room_lights
        # - group.hallway_lights
        # - group.kitchen_lights
        - light.clock_led_strip
        - light.tv_ambilight
      include_domains:
        - switch
        - cover
        - input_boolean
        - media_player

      # exclude_entities:
      # exclude_domains:
      #   - light
      #   - media_player
    entity_config:
      light.clock_led_strip:
        name: Clock
        display_categories: LIGHT
      light.tv_ambilight:
        name: TV backlight
        display_categories: LIGHT
      switch.pihole:
        name: Firewall
      sensor.living_room_temperature:
        name: Living Room Temperature
        display_categories: TEMPERATURE_SENSOR
      sensor.bedroom_temperature:
        name: Bedroom Temperature
        display_categories: TEMPERATURE_SENSOR

http:
  # base_url: !secret http_base_url
  # server_port: !secret http_port
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Discover some devices automatically
discovery:
  # ignore:
   # - samsung_tv
#   - roku
#   - google_cast

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
  include_used_components: true

sun:

ifttt:
  key: !secret ifttt_key

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.cuckoo_clock
      # - binary_sensor.office_motion
      - py.warnings
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.time
      - sensor.date
      - sensor.ha_uptime
    domains:
      - sun
      - binary_sensor
      - camera
      - device_tracker
      - group
      - input_number
      - input_text
      - script
      - sensor
      - weather
      - zone
      - automation
      - media_player

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover
    entities:
      - group.entry_points
  exclude:
    domains:
      - updater
      - automation
      - device_tracker
      - group
      - scene
      - script
      - weblink
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      # - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_uv_index
      - sensor.database_sensor
      - sensor.date
      - sensor.external_ip
      - sensor.ha_uptime
      - sensor.last_message
      - sensor.low_battery
      - sensor.moon
      - sensor.network
      - sensor.network_detail
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_unique_clients
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.speech_time
      - sensor.tesla
      - senswor.usdinr
      - sensor.time
      - sun.sun
      - zone.home
      - sensor.ist

mqtt:
  broker: !secret mqtt_broker_url
  port: 1883
  client_id: home-assistant-harshit
  # username: !secret MQTT_username
  # password: !secret MQTT_password

tts:
  # - platform: google
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    text_type: ssml
    cache: True
    # https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
    # https://console.aws.amazon.com/polly/home/SynthesizeSpeech
    voice: Joanna
    # cache_dir: /data/tts

# Media Players
# TODO - add universal media player - https://www.home-assistant.io/components/media_player.universal/

# cast:
#   media_player:
#     host:
#       - 192.168.1.80
#       - 192.168.1.30
#       - 192.168.1.82

media_player:
  - platform: plex
    entity_namespace: 'plex'
    # include_non_clients: true
    # show_all_controls: true
    use_episode_art: true
    remove_unavailable_clients: true
    # use_custom_entity_ids: true

  - platform: androidtv
    name: Fire TV 1
    host: 192.168.1.81

  - platform: samsungtv
    host: !secret samsung_tv_ip

  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    # aliases:
        # abc123def456: 'Living Room'
        # 9183abas000: 'Bed Room'

remote:
  - platform: harmony
    name: livingroom
    host: !secret harmony_ip

# apple_tv:
#   - host: 192.168.1.229
#     name: Apple TV

# Kodi
#media_player:
#  platform: kodi
#  host: http://192.168.1.80
#  port: 8090
#  name: Kodi on TV
#  user: kodi
#  password:
#  turn_off_action: none #The desired turn off action. Options are none, quit, hibernate, suspend, reboot, or shutdown. Default none.
#  enable_websocket: true


# Cameras
# camera:
# - platform: mjpeg
#   mjpeg_url: !secret camera1_mjpeg_url
#   still_image_url: !secret camera1_snapshot_url
#   username: !secret camera1_username
#   password: !secret camera1_password
#   name: Hallway Camera

camera:
  name: Family Map
  platform: generic
  still_image_url: !secret google_static_map_url
  limit_refetch_to_url_change: true

#binary_sensor:
#  - platform: rest
#    name: Entrance Motion
#    sensor_class: motion
#    resource: http://192.168.1.71:8080/sensors.json?sense=motion_active
#    value_template: '{{ value_json.motion_active.data[0][1][0] | round(0) }}'


# android_ip_webcam:
#   # This should be the ip of your phone
#   - host: 192.168.1.71
#     name: "Android IP Camera"
#     username: harct
#     password: hetarshit
#     scan_interval: 4
#     motion_sensor: true
#     sensors:
#     - motion
#     switches:
#     - night_vision
#     - torch
#     - video_recording

google:
  client_id: !secret google_clientid
  client_secret: !secret google_clientsecret

# Mailgun
mailgun:
  domain: !secret mailgun_domain
  api_key: !secret mailgun_api_key

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token


###############################################################
######  Merge Include Files
###############################################################

frontend: !include frontend.yaml
group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
light: !include_dir_merge_list lights
automation: !include automations.yaml
automation old: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
shell_command: !include_dir_merge_named shell_command
# zone: !include_dir_list zones
weblink: !include weblink.yaml
logger: !include logger.yaml
recorder: !include recorder.yaml
