homeassistant:
  name: SanghviHA
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/New_York

  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "sensor.dark_sky_*":
      homebridge_hidden: true

  packages: !include_dir_named packages

# Enables configuration UI
config:

cloud:
  alexa:
    filter:
      include_entities:
        # - group.all_lights
        # - group.all_switches
        # - group.interior_lights
        # - group.bedroom_lights
        # - group.living_room_lights
        # - group.living_room_accents
        # - group.dinette_lights
        # - group.dining_room_lights
        # - group.hallway_lights
        # - group.kitchen_lights
        - light.clock_led_strip
        - light.tv_ambilight
      include_domains:
        - switch
        - cover
        - input_boolean
        - media_player

      # exclude_entities:
      # exclude_domains:
      #   - light
      #   - media_player
    entity_config:
      light.clock_led_strip:
        name: Clock
        display_categories: LIGHT
      light.tv_ambilight:
        name: TV backlight
        display_categories: LIGHT
      switch.pihole:
        name: Network Filter
      sensor.living_room_temperature:
        display_categories: TEMPERATURE_SENSOR


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

http:
  # base_url: !secret http_base_url
  # server_port: !secret http_port
  api_password: !secret http_api_password
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  # trusted_networks:
    # - 192.168.1.0/24
    # - !secret external_ip
  ip_ban_enabled: True
  login_attempts_threshold: 5

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token


# Enables the frontend
frontend:
  javascript_version: latest

# Discover some devices automatically
discovery:
  # ignore:
   # - samsung_tv
#   - roku
#   - google_cast

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
  include_used_components: true

sun:

ifttt:
  key: !secret ifttt_key

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.cuckoo_clock
      # - binary_sensor.office_motion
      - py.warnings
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.time
      - sensor.date
      - sensor.ha_uptime
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover

  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
     - sensor.pihole_ads_blocked_today
     - sensor.pihole_ads_percentage_blocked_today
     - sensor.pihole_dns_queries_today
     - sensor.since_last_boot
     - sensor.since_last_boot_templated
     - sensor.ha_uptime
     - sensor.time

# logger: !include logger.yaml

# recorder: !include recorder.yaml
#
recorder:
  purge_keep_days: 7
  purge_interval: 1

mqtt:
  broker: 127.0.0.1
  port: 1883

input_number:
  clock_animation_speed:
    name: Clock Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

# Media Players
# TODO - add universal media player - https://www.home-assistant.io/components/media_player.universal/

media_player:
  - platform: cast
    host:
      - 192.168.1.80
      - 192.168.1.30
      - 192.168.1.82
  - platform: plex
    include_non_clients: true
    show_all_controls: true
    use_episode_art: true


# apple_tv:
#   - host: 192.168.1.229
#     login_id: 00000000-4ed1-c48d-9df9-df88baa045bc
#     name: Apple TV (Wired)

# Kodi
#media_player:
#  platform: kodi
#  host: http://192.168.1.80
#  port: 8090
#  name: Kodi on TV
#  user: kodi
#  password:
#  turn_off_action: none #The desired turn off action. Options are none, quit, hibernate, suspend, reboot, or shutdown. Default none.
#  enable_websocket: true


# Cameras
camera:
- platform: mjpeg
  mjpeg_url: !secret camera1_mjpeg_url
  still_image_url: !secret camera1_snapshot_url
  username: !secret camera1_username
  password: !secret camera1_password
  name: Hallway Camera


#binary_sensor:
#  - platform: rest
#    name: Entrance Motion
#    sensor_class: motion
#    resource: http://192.168.1.71:8080/sensors.json?sense=motion_active
#    value_template: '{{ value_json.motion_active.data[0][1][0] | round(0) }}'


# android_ip_webcam:
#   # This should be the ip of your phone
#   - host: 192.168.1.71
#     name: "Android IP Camera"
#     username: harct
#     password: hetarshit
#     scan_interval: 4
#     motion_sensor: true
#     sensors:
#     - motion
#     switches:
#     - night_vision
#     - torch
#     - video_recording


# camera:
#   - platform: usps
#     scan_interval: 5

# usps:
#     name: USPS Mail
#     username: !secret uspsmychoice_username
#     password: !secret uspsmychoice_password
#     driver: phantomjs
#     # https://stackoverflow.com/questions/36314771/how-to-install-phantomjs-for-use-with-python-selenium-on-the-raspberry-pi



tts:
  # - platform: google
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    text_type: ssml
    cache: True
    # https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
    # https://console.aws.amazon.com/polly/home/SynthesizeSpeech
    voice: Joanna
    # cache_dir: /data/tts

###############################################################
######  Merge Include Files
###############################################################

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
light: !include_dir_merge_list lights
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
# zone: !include_dir_list zones
weblink: !include weblink.yaml
