alias: Commute delay - Heta's morning
trigger:
  platform: numeric_state
  entity_id: sensor.her_morning_commute
  above: 150
condition:
- condition: time
  after: '07:00:00'
  before: '09:00:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
- condition: state
  entity_id: input_boolean.delay_alerts
  state: 'on'
- condition: state
  entity_id: device_tracker.life360_heta
  state: 'home'
action:
  - service: notify.ios_family
    data:
      message: "Commute delay of {{ trigger.to_state.state|round }} minutes for Heta"
      subtitle: "Home Assistant Notify"
