alias: Commute delay - Heta's morning
trigger:
  platform: numeric_state
  entity_id: sensor.her_morning_commute
  above: 120
condition:
- condition: time
  after: '07:00:00'
  before: '09:00:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
- condition: state
  entity_id: input_boolean.delay_alerts
  state: 'on'
- condition: state
  entity_id: device_tracker.hetas_iphone
  state: 'home'
action:
  - service: script.notify_engine
    data_template:
      who: 'family'
      value1: "Commute delay of {{ trigger.to_state.state|round }} minutes for Harshit"
