alias: Commute delay - Heta's evening
initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: sensor.her_evening_commute
    above: 150
condition:
  - condition: time
    after: '16:30:00'
    before: '18:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: switch.delay_alerts
    state: 'on'
  - condition: state
    entity_id: device_tracker.life360_heta
    state: 'not_home'
action:
  - service: script.notify_engine
    data_template:
      who: 'family'
      value1: "Commute delay notice"
      value2: "{{ trigger.to_state.state|round }} minutes for Heta"
