alias: Commute delay - Heta's evening
trigger:
  platform: numeric_state
  entity_id: sensor.her_evening_commute
  above: 150
condition:
- condition: time
  after: '15:45:00'
  before: '17:30:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
- condition: state
  entity_id: input_boolean.delay_alerts
  state: 'on'
- condition: state
  entity_id: device_tracker.hetas_iphone
  state: 'not_home'
action:
  - service: notify.ios_family
    data:
      message: "Commute delay of {{ trigger.to_state.state|round }} minutes for Heta"
      subtitle: "Home Assistant Notify"
