alias: Commute delay - Harshit's morning
trigger:
  platform: numeric_state
  entity_id: sensor.his_morning_commute
  above: 45
condition:
- condition: time
  after: '08:00:00'
  before: '10:15:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
- condition: state
  entity_id: input_boolean.delay_alerts
  state: 'on'
- condition: state
  entity_id: device_tracker.life360_harshit
  state: 'home'
action:
  - service: notify.ios_family
    data:
      message: "Commute delay of {{ trigger.to_state.state|round }} minutes for Harshit"
      subtitle: "Home Assistant Notify"
