alias: Commute delay - Harshit's morning
initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: sensor.his_morning_commute
    above: 30
condition:
  - condition: time
    after: '08:45:00'
    before: '10:30:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: switch.delay_alerts
    state: 'on'
  - condition: state
    entity_id: device_tracker.life360_harshit
    state: 'home'
action:
  - service: script.notify_engine
    data_template:
      who: 'family'
      value1: "Commute delay notice"
      value2: "{{ trigger.to_state.state|round }} minutes for Harshit"
