alias: Commute delay - Harshit's evening
trigger:
  platform: numeric_state
  entity_id: sensor.his_evening_commute
  above: 50
condition:
- condition: time
  after: '16:30:00'
  before: '18:30:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
- condition: state
  entity_id: input_boolean.delay_alerts
  state: 'on'
- condition: state
  entity_id: device_tracker.life360_harshit
  state: 'not_home'
action:
  - service: notify.ios_family
    data:
      message: "Commute delay of {{ trigger.to_state.state|round }} minutes for Harshit"
      subtitle: "Home Assistant Notify"
