- alias: Alert Mode On
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.alert_mode
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: group.all_lights
      data:
        brightness: 255
        color_name: red

    - service: script.dog_bark
