- alias: Alert if door was left open
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.main_door
        - binary_sensor.fridge_door
      to: 'on'
      for:
        seconds: 60
  action:
    - service: script.notify_engine
      data_template:
        who: 'home'
        value1: 'The {{ trigger.to_state.attributes.friendly_name }} is open!'
        value2: 'Please close it.'

    - service: script.speech_engine
      data_template:
        value1: 'The {{ trigger.to_state.attributes.friendly_name }} is open! Please close it.'

- alias: Alert if deadbolt was left open when home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.main_door
      to: 'off'
      for:
        seconds: 120

  condition:
    - condition: state
      entity_id: binary_sensor.deadbolt
      state: 'on'

    - condition: state
      entity_id: binary_sensor.media_room_motion
      state: 'on'

  action:
    - service: script.notify_engine
      data_template:
        who: 'home'
        value1: 'The deadbolt is open!'
        value2: 'Please lock it'

    - service: script.speech_engine
      data_template:
        value1: 'The deadbolt is open! Please lock it.'
