- alias: Alert if door was left open
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.main_door
        - binary_sensor.fridge_door
      to: 'on'
      for:
        seconds: 60
  action:
    - service: script.notify_engine
      data_template:
        who: 'family'
        value1: 'The {{ trigger.to_state.attributes.friendly_name }} is open! Please close it.'

    - service: script.speech_engine
      data_template:
        value1: 'The {{ trigger.to_state.attributes.friendly_name }} is open! Please close it.'
