###################################
## @CCOSTAN
## Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################

- alias: Door Chime
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - group.entry_points

  condition:
    - condition: state
      entity_id: group.family
      state: 'home'

  action:
    - service: script.play_custom_media
      data_template:
        media_content_id: >
          {% if trigger.to_state.state == 'on' %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/one-tone-chime.mp3
          {% else %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/two-tone-chime.mp3
          {% endif %}
        media_content_type: audio/mp4
