######################################################################
##  Door Open Announcements
######################################################################
- alias: 'Intruder Alert'

  trigger:
    - platform: state
      entity_id:
        - binary_sensor.entry_points # Front door #
      from: 'off'
      to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'

  # condition:
  #   - condition: state
  #     entity_id: binary_sensor.sleepnumber_carlo_carlo_is_in_bed
  #     state: 'on'
  #   - condition: state
  #     entity_id: binary_sensor.sleepnumber_carlo_stacey_is_in_bed
  #     state: 'on'

  action:
    - service: script.notify_engine
      data_template:
        who: 'harshit'
        value1: "The {{ trigger.to_state.attributes.friendly_name }} was opened."

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.speech_engine
      data_template:
        value1: 'Intruder detected. Please leave or I am alerting the authorities.'

    - service: light.turn_on
      entity_id:
        - group.interior_lights
      data_template:
        color_name: red
