# TODO Add dash button and xiaomi buttons

- platform: mqtt
  name: "Round Button 1"
  command_topic: "smartthings/Round Button 1/button"
  state_topic: "smartthings/Round Button 1/button"
  payload_on: "pushed"
  payload_off: "released"

- platform: mqtt
  name: "Square Button 1"
  command_topic: "smartthings/Square Button 1/button"
  state_topic: "smartthings/Square Button 1/button"
  payload_on: "pushed"
  payload_off: "released"
