- platform: template
  switches:
    sonos_speech_enhance:
      friendly_name: Sonos Speech Enhance
      value_template: "{{state_attr('media_player.media_room','speech_enhance')}}"
      turn_on:
        - service: media_player.sonos_set_option
          data:
            entity_id: media_player.media_room
            speech_enhance: True
      turn_off:
        - service: media_player.sonos_set_option
          data:
            entity_id: media_player.media_room
            speech_enhance: False
    sonos_night_sound:
      friendly_name: Sonos Night Sound
      value_template: "{{state_attr('media_player.media_room','night_sound')}}"
      turn_on:
        - service: media_player.sonos_set_option
          data:
            entity_id: media_player.media_room
            night_sound: True
      turn_off:
        - service: media_player.sonos_set_option
          data:
            entity_id: media_player.media_room
            night_sound: False
