##########  ############################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'People Greeting'
  trigger:
    - platform: state
      entity_id:
        - device_tracker.harshits_iphone
        - device_tracker.hetas_iphone
      from: 'not_home'
      to: 'home'
      # for: '00:01:00'
  condition:
    - condition: time
      after: '16:30:00'
      before: '01:00:00'
    # TODO - Make it run only once in the day for each person
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.people_greeting.attributes.last_triggered) | int > 10 }}'

  action:

    # http://jinja.pocoo.org/
    - wait_template: >-
        {% set person = trigger.entity_id.split(".")[1].split("_")[0] %}
        {% set person_device = 'device_tracker.' + person + 'iphonesanghvihome' %}
        {{ is_state('person_device', 'home') }}
      timeout: '00:15:00'
    - wait_template: >-
        {{ not is_state('media_player.apple_tv_wired', 'playing') }}
      timeout: '00:01:00'

    - service: script.speech_engine
      data_template:
        # {% set person = states[trigger.entity_id.split(".")[0]][trigger.entity_id.split(".")[1]].name%}
        personarriving: >
          {% set person = trigger.from_state.attributes.friendly_name%}
          {%- macro greeting_sentence(person) -%}
          {{ [
          "Welcome back home " ~ person,
          "Guess who is home?" ~ person +" is!",
          person + " is now in the house.",
          "Welcome Home " ~ person + ".  We have missed you.",
          "Our home is now complete, Rest your head and relax your feet! Welcome Back " ~ person,
          "Life is like a song, you’re back where you belong. Welcome home " ~ person,
          "Hey there " ~ person + " Welcome Home!",
          "Knock Knock. Who is There? "   ~ person +" is!",
          person ~ "! You are home!",
          "I know a secret! "  ~ person +" is home!"
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence(person)}}
        call_no_announcement: 1

##########  ############################################################
##  Announce when friends come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'Friends Greeting'
  trigger:
    - platform: state
      entity_id:
        - device_tracker.salonisanghvihome
        - device_tracker.neelshahsiphonesanghvihome
        - device_tracker.kalpanasiphonesanghvihome
        - device_tracker.android4d7dd24268c2601csanghvihome

      from: 'not_home'
      to: 'home'
      # for: '00:01:00'
  condition:
    - condition: time
      after: '11:00:00'
      before: '21:00:00'
    # TODO - Make it run only once in the day for each person
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.people_greeting.attributes.last_triggered) | int > 1440 }}'

  action:
    - service: script.speech_engine
      data_template:
        # {% set person = states[trigger.entity_id.split(".")[0]][trigger.entity_id.split(".")[1]].name%}
        personarriving: >
          {% set person = trigger.from_state.attributes.friendly_name%}
          {%- macro greeting_sentence(person) -%}
          {{ [
          "Welcome back home " ~ person,
          person + " is now in the house.",
          "Welcome Home " ~ person + ".  We have missed you.",
          "Hey there " ~ person + " Welcome Home!",
          "Knock Knock. Who is There? "   ~ person +" is!",
          person ~ "! You are home!",
          "I know a secret! "  ~ person +" is home!"
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence(person)}}
        call_no_announcement: 1
