######################################################################
##  Some home facts when we get back home from being away.
######################################################################
- alias: 'Home Stats'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - group.family
      from: 'not_home'
      to: 'home'

    - platform: state
      entity_id: input_boolean.home_stats
      to: 'on'
      from: 'off'

  action:

    - wait_template: "{{ is_state('group.main_door', 'closed') }}"
      timeout: 00:01:00

    - wait_template: "{{ is_state('group.main_door', 'open') }}"
      timeout: 00:15:00

    - wait_template: "{{ is_state('group.main_door', 'closed') }}"
      timeout: 00:05:00

    - service: script.speech_engine
      data:
        call_inside_weather: 1
        call_outside_weather: 1
        # call_garage_check: 1
        call_window_check: 1
        call_light_check: 1
