##############################################################################
###  New Device has connected to the network.  let everyone know.
##############################################################################

- alias: "New device connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device

  action:
    - wait_template: >-
        {{ not is_state('media_player.apple_tv_wired', 'playing') }}

    - service: script.notify_engine
      data_template:
        who: 'harshit'
        value1: "New device detected on the network.
        value2: "{{trigger.event.data.host_name}} - {{trigger.event.entity_id}}"

    - service: script.speech_engine
      data_template:
        NewDevice: "New device detected on the network. Be sure to appropriately catagorize {{trigger.event.data.host_name}} - {{trigger.event.entity_id}}."

    - service: script.tweet_engine
      data_template:
        tweet: >
          {{ [
          "New Device on the Network!",
          "Constant monitoring of the network by #nmap has detected a new device in the environment."
          ] | random }}
##############################################################################
