speech_notifications:
  name: Speech Notifications
  icon: mdi:speaker-wireless
  initial: on

text_notifications:
  name: Text Notifications
  icon: mdi:cellphone-wireless
  initial: on

delay_alerts:
  name: Delays Alert
  initial: on
  icon: mdi:car-connected

workday:
  name: Workday
  initial: off
