###################################################
## Various MQTT sensors
###################################################

- platform: mqtt
  name: Living Room Temperature
  unit_of_measurement: '°C'
  state_topic: "smartthings/Living Room Temperature/temperature"

- platform: mqtt
  name: Living Room Humidity
  unit_of_measurement: '%'
  state_topic: "smartthings/Living Room Temperature/humidity"

