- platform: plex
  host: !secret plex_host
  name: !secret plex_name
  username: !secret plex_username
  password: !secret plex_password
  server: !secret plex_server
  token: !secret plex_token
  ssl: false

- platform: tautulli
  host: !secret plex_host
  api_key: !secret tautulli_api
  monitored_conditions:
    - stream_count
    - stream_count_transcode
    - stream_count_direct_play
    - stream_count_direct_stream
    - total_bandwidth
