- platform: plex
  host: !secret plex_host
  name: !secret plex_name
  username: !secret plex_username
  password: !secret plex_password
  server: !secret plex_server
  token: !secret plex_token
  ssl: false
