- platform: template
  sensors:
    portfolioval:
      friendly_name: "Portfolio Value"
      unit_of_measurement: "$"
      value_template: >-
         {%- if states.input_number.portfoliovalue.state != None -%}
           {{states.input_number.portfoliovalue.state|default(0)|round(2)}}
         {%- else -%}
           0
         {%- endif -%}
    portfoliochange:
      friendly_name: "Portfolio Change"
      unit_of_measurement: "$"
      value_template: >-
         {%- if states.input_number.portfoliochange.state != None -%}
           {{states.input_number.portfoliochange.state|default(0)|round(2)}}
         {%- else -%}
           0
         {%- endif -%}
    portfoliochange2:
      friendly_name: "Portfolio Change (PC)"
      unit_of_measurement: "$"
      value_template: >-
         {{(states('sensor.pc_investment')|float - states('sensor.portfolio_morning')|float)|round (2)}}
