- platform: rest
  scan_interval: 3600
  resource: 'http://api.forismatic.com/api/1.0/?method=getQuote&format=text&lang=en'
  method: GET
  name: Quote
  value_template: '{{value.split(" (")[0]}}'
# Horoscope API - http://sandipbgt.com/theastrologer/api/
- platform: rest
  scan_interval: 7200
  resource: !secret his_horoscope_url
  name: His Horoscope
  value_template: "{{ value_json.horoscope }}"
- platform: rest
  scan_interval: 7200
  resource: !secret her_horoscope_url
  name: Her Horoscope
  value_template: "{{ value_json.horoscope }}"
