- platform: rest
  scan_interval: 3600
  resource: 'http://api.forismatic.com/api/1.0/?method=getQuote&format=text&lang=en'
  method: GET
  name: Quote
  value_template: '{{value.split(" (")[0]}}'
# Horoscope API -
# http://sandipbgt.com/theastrologer/api/
# https://github.com/sandipbgt/theastrologer-api - http://theastrologer-api.herokuapp.com/api
- platform: rest
  scan_interval: 1800
  resource: !secret his_horoscope_url
  name: His Horoscope
  value_template: "{{ value_json.horoscope | truncate(255)}}"
- platform: rest
  scan_interval: 1800
  resource: !secret her_horoscope_url
  name: Her Horoscope
  value_template: "{{ value_json.horoscope | truncate(255) }}"
