# see how many new commit there are.
# TODO not working
# - platform: command_line
#   name: New Commits
#   scan_interval: 600
#   unit_of_measurement: commits
#   command: "git fetch origin && git log master..origin/master --pretty=oneline | wc -l"

# Track how many errors are in the log.
- platform: command_line
  name: Home Assistant Errors
  scan_interval: 30
  unit_of_measurement: errors
  command: grep -r "ERROR" home-assistant.log | wc -l
# Track how many warnings are in the log.
- platform: command_line
  name: Home Assistant Warnings
  scan_interval: 30
  unit_of_measurement: warnings
  command: grep -r "WARNING" home-assistant.log | wc -l

# Track number of connected clients.
- platform: api_streams
