# Track how many errors are in the log.
- platform: command_line
  name: Home Assistant Errors
  scan_interval: 1800
  unit_of_measurement: errors
  command: grep -r -E ":[0-9][0-9] ERROR" /home/pi/.homeassistant/home-assistant.log | wc -l
# Track how many warnings are in the log.
- platform: command_line
  name: Home Assistant Warnings
  scan_interval: 1800
  unit_of_measurement: warnings
  command: grep -r -E ":[0-9][0-9] WARNiNG" /home/pi/.homeassistant/home-assistant.log | wc -l

# Track number of connected clients.
- platform: api_streams
