- platform: darksky
  api_key: !secret forecast_key
  monitored_conditions:
#    - summary
#    - precip_type
    - precip_intensity
    - precip_intensity_max
    # - temperature
    - apparent_temperature
#    - dew_point
    - wind_speed
#    - wind_bearing
    - cloud_cover
    - humidity
#    - nearest_storm_distance
    - minutely_summary
#    - pressure
#    - visibility
#    - ozone
    - uv_index
    # - icon

- platform: moon

#sensor yweather:
#  platform: yweather
  #woeid: YOUR_WOEID
#  forecast: 0
#  monitored_conditions:
#   - weather
   #- weather_current
   #- temp_min
   #- temp_max
   #- wind_speed
   #- pressure
   #- visibility
   #- humidity
   #- temperature
