######################################################################
##  Alarm lights
######################################################################

- alias: 'Entry Point Alert'
  trigger:
    - platform: state
      entity_id:
        - group.entry_points

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      # - condition: state
      #   entity_id: group.bed
      #   state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - group.living_room_accents
      data_template:
        color_name: >
          {% if states.group.entry_points.state == 'on' -%}
          red
          {% else %}
          gold
          {% endif %}
