automation: 
  - alias: "Clock Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.clock_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "sanghvi/clocklight/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
