######################################################################
##  Color Tornado!
######################################################################
- alias: 'Color Tornado'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.color_tornado
      to: 'on'
      from: 'off'

  action:
    - service: light.lifx_effect_colorloop
      data:
        entity_id: group.main_lights
        brightness: 255
        period: 10
        spread: 30
        change: 35

    - service: input_boolean.turn_off
      entity_id: input_boolean.color_tornado
