######################################################################
##  TV Time at sunset or 8pm.  Whichever is later.
######################################################################

- alias: Find my iPhone
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.find_my_iphone_harshit
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: input_boolean.find_my_iphone_heta
      to: 'on'
      from: 'off'

  action:
    - service: device_tracker.icloud_lost_iphone
      data_template:
        device_name: >-
          {% if (trigger.entity_id == 'input_boolean.find_my_iphone_heta') %}
            hetasiphone
          {% else %}
            harshitsiphone
          {% endif %}

    - service: input_boolean.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
