######################################################################
##  TV Time at sunset or 8pm.  Whichever is later.
######################################################################

- alias: Find my iPhone
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.find_my_iphone_harshit
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: input_boolean.find_my_iphone_heta
      to: 'on'
      from: 'off'

  action:
    - service: device_tracker.icloud_lost_iphone
      data_template:
        device_name: >-
          {% if (trigger.entity_id == 'input_boolean.find_my_iphone_heta') %}
            hetasiphone
          {% else %}
            harshitsiphone
          {% endif %}
        account_name: >-
          {% if (trigger.entity_id == 'input_boolean.find_my_iphone_heta') %}
            heta
          {% else %}
            harshit
          {% endif %}
    - service: input_boolean.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"


- alias: Reset iCloud interval to max
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: 30

  action:
    - service: device_tracker.icloud_set_interval
      data_template:
        interval: 360
