######################################################################
##  Flash all the lights!
######################################################################
- alias: 'Flash all_lights'
  trigger:
    - platform: state
      entity_id: input_boolean.flash
      to: 'on'
      from: 'off'
    - platform: event
      event_type: flash_all

  action:
    # https://www.home-assistant.io/components/light.lifx/
    - service: light.lifx_effect_pulse
      data:
        entity_id:
          - group.living_room_lights
          - group.kitchen_lights
          - group.hallway_lights
          - group.bedroom_lights

    - service: input_boolean.turn_off
      entity_id: input_boolean.flash
