# - alias: "Internet Speed Great"
#   trigger:
#     - platform: template
#       value_template: "{{ states('sensor.speedtest_download')|float >= 80 }}"
#   action:
#     - service: script.speech_engine
#       data_template:
#         value1: 'The internet speed is good! Download: {{ states('sensor.speedtest_download') }} | Upload: {{ states('sensor.speedtest_download') }} | Ping: {{ states('sensor.speedtest_ping') }}'


- alias: "Internet Speed Poor"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.speedtest_download')|float < 10 }}"
  action:
    - service: script.speech_engine
      data_template:
        value1: "The internet speed is low again! Download: {{ states('sensor.speedtest_download') }} | Upload: {{ states('sensor.speedtest_download') }} | Ping: {{ states('sensor.speedtest_ping') }}"
    - service: script.notify_engine
      data_template:
        who: 'harshit'
        value1: "The internet speed is low again!"
        value2: "Download: {{ states('sensor.speedtest_download') }} | Upload: {{ states('sensor.speedtest_download') }} | Ping: {{ states('sensor.speedtest_ping') }}"
