######################################################################
##  Stuff that needs to happen after 10pm.
######################################################################

######################################################################
##  Stuff that needs to happen after 10pm.
######################################################################

- alias: Automated Night WatchDog
  trigger:
    - platform: state
      entity_id: light.all_lights
      to: 'on'
      for: '00:10:00'

  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: group.family
            state: 'not_home'
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'off'
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'off'
      - condition: time
        after: '01:00:00'
        before: '06:00:00'

  action:
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
