- alias: Workday Switch
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.workday
    - platform: state
      entity_id: binary_sensor.workday_sensor

  action:
    - service_template: "homeassistant.turn_{{ 'on' if trigger.to_state.state == 'on' else 'off' }}"
      data:
        entity_id: input_boolean.workday
