- platform: nmap_tracker
  hosts:
    - 192.168.1.0/24
    # - 192.168.1.15
    # - 192.168.1.16
    # - 192.168.1.100
  home_interval: 20
#    exclude:
#     - 192.168.1.175
#     - 192.168.1.176
  interval_seconds: 60
  # 5 minutes
  consider_home: 0:02:00
  track_new_devices: yes
#  scan_options: " --privileged -sP "
