- platform: nmap_tracker
  hosts:
  - 192.168.1.15
  - 192.168.1.16
  home_interval: 20
#    exclude:
#     - 192.168.1.175
#     - 192.168.1.176
  interval_seconds: 120
  consider_home: 60
#  scan_options: " --privileged -sP "
#  consider_home: 1800 - Added to known_devices.yaml instead on a device by device basis.
