#########################################################################
# Geographic
#
#  Anything to do with zones, travel, etc.
#########################################################################

homeassistant:
  customize:
    proximity.home:
      friendly_name: Anyone's proximity
    proximity.her_home:
      friendly_name: Her proximity
    proximity.his_home:
      friendly_name: His proximity
    sensor.him_to_her:
      icon: mdi:heart
  customize_glob:
    'sensor.*morning_commute':
      icon: mdi:briefcase
    'sensor.*evening_commute':
      icon: mdi:home

# Group geo-related entities.
group:
  Geo:
    - sensor.him_to_her
    - sensor.his_morning_commute
    - sensor.his_evening_commute
    # - sensor.her_morning_commute
    # - sensor.her_evening_commute
    - sensor.her_distance_mean
    - sensor.his_distance_mean
    - proximity.her_home
    - proximity.his_home
    - proximity.home
    - sensor.his_departure_time
    - sensor.her_departure_time
    - sensor.traveling_away
    - sensor.traveling_home
  Travel Times:
    - sensor.his_morning_commute
    - sensor.his_evening_commute
    # - sensor.her_morning_commute
    # - sensor.her_evening_commute

zone:
  # Home zone.
  - name: Home
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude
    radius: 150
    icon: mdi:account-multiple

  # His work location.
  - name: His Work
    latitude: !secret his_work_latitude
    longitude: !secret his_work_longitude
    radius: 150
    icon: mdi:worker

  # # Her work location.
  # - name: Her Work
  #   latitude: !secret her_work_latitude
  #   longitude: !secret her_work_longitude
  #   radius: 5
  #   icon: mdi:worker

  # Her home (for proximity tracking).
  - name: Her Home
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_latitude
    radius: 150
    passive: true
    icon: mdi:account-multiple
  # His home (for proximity tracking).
  - name: His Home
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_latitude
    radius: 150
    passive: true
    icon: mdi:account-multiple

proximity:
  # Her proximity to home.
  her_home:
    devices:
      - device_tracker.life360_heta
    tolerance: 50
    unit_of_measurement: 'km'
  # His proximity to home.
  his_home:
    devices:
      - device_tracker.life360_harshit
    tolerance: 50
    unit_of_measurement: 'km'
  # Nearest proximity to home.
  home:
    devices:
      - device_tracker.life360_harshit
      - device_tracker.life360_heta
    tolerance: 50
    unit_of_measurement: 'km'

# TODO - automations based on the traveling direction sensors e.g. set thermostat
binary_sensor:
  - platform: trend
    sensors:
      traveling_home:
        entity_id: proximity.his_home
        invert: true
      traveling_away:
        entity_id: proximity.his_home


sensor:
  # His home departure time.
  - platform: mqtt
    name: "His Departure Time"
    state_topic: "home/departure/harshit"
  # Her home departure time.
  - platform: mqtt
    name: "Her Departure Time"
    state_topic: "home/departure/heta"

  # His average distance from home.
  - platform: statistics
    name: His Distance
    entity_id: proximity.his_home
  # Her average distance from home.
  - platform: statistics
    name: Her Distance
    entity_id: proximity.her_home

  # Travel time on his morning commute.
  - platform: google_travel_time
    name: His Morning Commute
    api_key: !secret google_api_key
    scan_interval: 60000
    origin: !secret home_address
    destination: !secret his_work_address
    options:
      mode: transit
  # Travel time on his evening commute.
  - platform: google_travel_time
    name: His Evening Commute
    scan_interval: 60000
    api_key: !secret google_api_key
    origin: !secret his_work_address
    destination: !secret home_address
    options:
      mode: transit

  # # Travel time on her morning commute.
  # - platform: google_travel_time
  #   name: Her Morning Commute
  #   scan_interval: 60000
  #   api_key: !secret google_api_key
  #   origin: !secret home_address
  #   destination: !secret her_work_address
  #   options:
  #     mode: transit
  # # Travel time on her evening commute.
  # - platform: google_travel_time
  #   name: Her Evening Commute
  #   scan_interval: 60000
  #   api_key: !secret google_api_key
  #   origin: !secret her_work_address
  #   destination: !secret home_address
  #   options:
  #     mode: transit

  # Travel time between him and her
  - platform: google_travel_time
    name: Him to Her
    scan_interval: 60000
    api_key: !secret google_api_key
    origin: device_tracker.life360_harshit
    destination: device_tracker.life360_heta
    options:
        mode: driving

automation:
  # Track and record departure time from home for everyone.
  - alias: Track Departure Time
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - device_tracker.life360_harshit
          - device_tracker.life360_heta
        from: home
        to: not_home
    action:
      - service: mqtt.publish
        data_template:
          topic: 'home/departure/{{trigger.entity_id.split(".")[1].split("_")[1]}}'
          payload: '{{now().hour}}:{{now().minute}}'
