#-------------------------------------------
#  Realtime Debugging Related Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
# homeassistant:
#   customize_glob:
#     "sensor.harshits_iphone_6*":
#
#     "sensor.staceys_iphone_*":

notify:
  - platform: ios
  - name: ios_family
    platform: group
    services:
      - service: ios_harshits_iphone
      - service: ios_hetas_iphone
  # - name: ios_parents
  #   platform: group
  #   services:
  #     - service: ios_staceys_iphone
  #     - service: ios_harshits_iphone_6s

# group:
#   Phones:
#     entities:
#       - sensor.harshits_iphone_6s_battery_level
#       - sensor.harshits_iphone_6s_battery_state
#       - sensor.staceys_iphone_battery_level
#       - sensor.staceys_iphone_battery_state

## - Reminders to take my medicine
ios:
  push:
    categories:
      - name: Medicine
        identifier: 'tablet'
        actions:
          - identifier: 'TABLET_TAKEN'
            title: 'Tablet Taken'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes

          - identifier: 'NOT_HOME'
            title: 'I am not Home'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no

## - Reminders to take my medicine
input_boolean:
  medicine:
    name: Medicine Reminder
    initial: off
    icon: mdi:tablet

automation:
  - alias: Tablet Already taken
    initial_state: 'on'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TABLET_TAKEN
    action:
      - service: notify.ios_family
        data:
          message: "Great job!"
      - service: input_boolean.turn_on
        entity_id: input_boolean.medicine

  - alias: Remind Me Later
    initial_state: 'on'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: NOT_HOME
    action:
      - service: notify.ios_family
        data:
          message: "Ok. I will remind you when you get home."
      - wait_template: >-
          {{ states.device_tracker.life360_harshit.state == 'home' }}
      - service: notify.ios_family
        data:
          message: "Now that your home, please take your medicine!"

  - alias: Medicine Reminder
    initial_state: 'on'
    trigger:
      - platform: time_pattern
        minutes: '/45'
      # - platform: time
      #   at: '21:00:00'
      - platform: state
        entity_id: device_tracker.life360_harshit
        to: 'home'

    condition:
      - condition: time
        after: '21:00:00'
      - condition: state
        entity_id: device_tracker.life360_harshit
        state: 'home'
      - condition: state
        entity_id: input_boolean.medicine
        state: 'off'

    action:
      - service: notify.ios_family
        data:
          title: "Medicine Alert!"
          message: "Please take your Medicine!"
          data:
            push:
              category: "tablet"
            action_data:
              # Anything passed in action_data will get echoed back to Home Assistant.
              entity_id: light.test
              my_custom_data: foo_bar

## Reminders to take my Medicine! - End.
