###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunrise Stuff'
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'

  action:
    - service: script.interior_off
    - delay: '00:{{ (range(1, 55)|random|int) }}:00'
    - service: homeassistant.turn_off
      entity_id:
        - group.living_room_lights
        - group.bedroom_lights
        - group.kitchen_lights

    - wait_template: >-
       {{ states.sun.sun.state == 'above_horizon' }}
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights

    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.medicine  # Reset medicine taken boolean for new day
        - input_boolean.daylight_override
        - input_boolean.guest_mode
