###################################
##  Sunrise and Sunset stuff
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################

- alias: 'Sunset'
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
      from: 'above_horizon'

  action:
    - service: script.tweet_engine_image
      data_template:
        tweet: >-
          {{ [
          "Right before sunset, I turn on the outside lights.",
          "Since it gets dark around sunset, I will turn on some lights.",
          "Time to turn on the outside lights.",
          "Daytime is over, Time to turn on the exterior lights.",
          "Once the Sun goes down, we turn on the exterior lights.",
          "Since it is sunset, I will turn on the exterior lights."
          ] | random + [
          " #Sunset",
          " #HomeAutomation",
          " #AccentLighting"
          ] | random }}
    - delay: '00:{{ (range(1, 20)|random|int) }}:00'
    - service: script.speech_engine
      data:
        call_dark_outside: 1
        # call_window_check: 1

    - service: script.monthly_color_scene
    - wait_template: >-
       {{ states.group.family.state == 'home' }}

    - service: switch.turn_on
      entity_id:
       - switch.rotimatic # TODO - change the name to TV
       - switch.bedroom_tv

    - delay: '00:{{ (range(2, 5)|random|int) }}:00'

    - service: light.turn_on
      entity_id:
       - light.clock_led_strip

    - service: light.turn_on
      entity_id:
       - light.tv_ambilight
    # 
    # - wait_template: >-
    #    {{ is_state('binary_sensor.main_door', 'on') }}
    # - wait_template: >-
    #    {{ is_state('binary_sensor.main_door', 'off') }}
    #
    # - service: script.speech_engine
    #   data:
    #    # call_garage_check: 1
    #    call_window_check: 1
