###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunset Stuff off'
  trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'

  action:
    - service: script.interior_off
    - service: homeassistant.turn_off
      entity_id:
        - group.hallway_lights
    - service: script.tweet_engine_image
      data_template:
        tweet: >
          {{ [
          "Even though they are sleeping, I still turn off the external lights before sunrise.",
          "It was a beautiful sunrise.  Time to turn off the exterior lights.",
          "If the sun is out, we do not need the exterior lights on.",
          "The sun is up so it is time to turn the outside lights off.",
          "Everyone will be up soon so time to turn off the outside lights.",
          "Good morning Twitter, the sun is up so it is time for me to turn the outside lights off."
          ] | random + "#HomeAutomation"}}
        image: >-
          {{ [
          "/config/www/custom_ui/floorplan/images/branding/sunrise.png",
          "/config/www/custom_ui/floorplan/images/branding/sunrise2.png",
          "/config/www/custom_ui/floorplan/images/branding/Bear_Stone_Coffee.png"
          ] | random }}

    - delay: '00:{{ (range(1, 55)|random|int) }}:00'
    - service: homeassistant.turn_off
      entity_id:
        - group.living_room_lights
        - group.bedroom_lights
        - group.kitchen_lights

    - wait_template: >-
       {{ states.sun.sun.state == 'above_horizon' }}
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights

    - service: input_boolean.turn_off
      entity_id:
        # - input_boolean.medicine
        - input_boolean.daylight_override
        # - input_boolean.guest_mode
