######################################################################
##  Daily reminders
######################################################################

- alias: 'Water the plants'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '20:00:00'

  condition:
    - condition: state
      entity_id: group.family
      state: 'home'

  action:
    - service: script.notify_engine
      data_template:
        who: 'home'
        value1: "Please water the plants"
